### ISSUE TITLE
`c_rehash` must be run on CA Cert Folder

### ISSUE THREAD

**Issue by daviddob** [Microsoft/service-fabric-cli#127]
When reporting a new issue include the following information:

- [x] `sfctl` version, can check this using `pip show sfctl`
```
6.0.0

Python (Linux) 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609]

Python location '/usr/bin/python'
```
- [x] Service Fabric cluster runtime version
```
6.3.129.1
```
- [x] Service Fabric hosting location (on-premise or Azure usually)
```
On-Premise - linux
```
- [x] Debug log if an error is present (can be captured using `--debug` flag)
```
Command arguments: ['--debug', 'cluster', 'select', '--endpoint', 'https://service-fabric.example.com:19080', '--cert', '/home/vagrant/test-certs/admin_client.crt', '--key', '/home/vagrant/test-certs/admin_client.key', '--ca', '/home/vagrant/test-certs/']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function on_global_arguments at 0x7fbbe1a1c410>, <function on_global_arguments at 0x7fbbe1a44050>, <function on_global_arguments at 0x7fbbe19db668>]
Event: CommandInvoker.OnPreCommandTableCreate [<function remove_logger_flags at 0x7fbbe1a1c488>]
Event: CommandLoader.OnLoadArguments []
Event: CommandInvoker.OnPostCommandTableCreate []
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs []
Event: CommandInvoker.OnPostParseArgs [<function handle_output_argument at 0x7fbbe1a440c8>, <function handle_query_parameter at 0x7fbbe19db6e0>]
msrest.service_client : Accept header absent and forced to application/json
msrest.pipeline : Configuring request: timeout=100, verify=True, cert=None
msrest.pipeline : Configuring proxies: ''
msrest.pipeline : Evaluate proxies against ENV settings: True
msrest.pipeline : Configuring redirects: allow=True, max=30
msrest.pipeline : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
urllib3.connectionpool : Starting new HTTPS connection (1): service-fabric.example.com:19080
urllib3.util.retry : Incremented Retry for (url='/'): Retry(total=2, connect=3, read=3, redirect=None, status=None)
urllib3.connectionpool : Retrying (Retry(total=2, connect=3, read=3, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),)': /
urllib3.connectionpool : Starting new HTTPS connection (2): service-fabric.example.com:19080
urllib3.util.retry : Incremented Retry for (url='/'): Retry(total=1, connect=3, read=3, redirect=None, status=None)
urllib3.connectionpool : Retrying (Retry(total=1, connect=3, read=3, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),)': /
urllib3.connectionpool : Starting new HTTPS connection (3): service-fabric.example.com:19080
urllib3.util.retry : Incremented Retry for (url='/'): Retry(total=0, connect=3, read=3, redirect=None, status=None)
urllib3.connectionpool : Retrying (Retry(total=0, connect=3, read=3, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),)': /
urllib3.connectionpool : Starting new HTTPS connection (4): service-fabric.example.com:19080
msrest.exceptions : Error occurred in request., SSLError: HTTPSConnectionPool(host='service-fabric.example.com', port=19080): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))
Error occurred in request., SSLError: HTTPSConnectionPool(host='service-fabric.example.com', port=19080): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))
Traceback (most recent call last):
  File "/home/vagrant/.local/lib/python2.7/site-packages/knack/cli.py", line 125, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/vagrant/.local/lib/python2.7/site-packages/knack/invocation.py", line 85, in execute
    cmd_result = parsed_args.func(params)
  File "/home/vagrant/.local/lib/python2.7/site-packages/knack/commands.py", line 67, in __call__
    return self.handler(*args, **kwargs)
  File "/home/vagrant/.local/lib/python2.7/site-packages/knack/commands.py", line 123, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "/home/vagrant/.local/lib/python2.7/site-packages/sfctl/custom_cluster.py", line 104, in select
    rest_client.send(rest_client.get('/')).raise_for_status()
  File "/home/vagrant/.local/lib/python2.7/site-packages/msrest/service_client.py", line 369, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "/home/vagrant/.local/lib/python2.7/site-packages/msrest/exceptions.py", line 57, in raise_with_traceback
    raise error
ClientRequestError: Error occurred in request., SSLError: HTTPSConnectionPool(host='service-fabric.example.com', port=19080): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))
```
Be sure to check if an issue already exists with your symptoms. If so, leave a `:thumbsup:` reaction to the original issue, rather than creating a duplicate.

When using a directory in the --ca flag, `c_rehash` must be run on the directory before attempting to run `sfctl cluster select` otherwise the CA certs in the directory will be ignored. This is not currently listed in the documentation of help materials - and the error message does not allude to this being the case (just that the cert is invalid)

**Comment by Christina-Kang** [comment]
Thank you so much, @daviddob for pointing this issue out to us and for updating the documentation for this issue! Very much appreciated! 

The documentation will be updated in the upcoming release, and we will look into making the requirement more clear in other places as well.
