### ISSUE TITLE
sfcli - not able to connect to cluster

### ISSUE THREAD

**Issue by binishababu** [microsoft/service-fabric-cli#160]
When reporting a new issue include the following information:

- [ ] `sfctl` version, can check this using `pip show sfctl` - 6.2.0
- [ ] Service Fabric cluster runtime version - 6.3.187.9494
- [ ] Service Fabric hosting location - Azure 
- [ ] Debug log if an error is present (can be captured using `--debug` flag)
 - Python version - Python 3.6.7
- Pip Version : pip 10.0.1
Be sure to check if an issue already exists with your symptoms. If so, leave a `:thumbsup:` reaction to the original issue, rather than creating a duplicate.
Log :
[('PEM routines', 'PEM_read_bio', 'no start line'), ('SSL routines', 'use_certificate_chain_file', 'PEM lib')]
Traceback (most recent call last):
  File "c:\users\cvcdev\appdata\local\programs\python\python36-32\lib\site-packages\knack\cli.py", line 125, in invoke
    cmd_result = self.invocation.execute(args)
  File "c:\users\cvcdev\appdata\local\programs\python\python36-32\lib\site-packages\knack\invocation.py", line 85, in execute
    cmd_result = parsed_args.func(params)
  File "c:\users\cvcdev\appdata\local\programs\python\python36-32\lib\site-packages\knack\commands.py", line 67, in __call__
    return self.handler(*args, **kwargs)
  File "c:\users\cvcdev\appdata\local\programs\python\python36-32\lib\site-packages\knack\commands.py", line 123, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "c:\users\cvcdev\appdata\local\programs\python\python36-32\lib\site-packages\sfctl\custom_cluster.py", line 95, in select
    rest_client.send(rest_client.get('/')).raise_for_status()
  File "c:\users\cvcdev\appdata\local\programs\python\python36-32\lib\site-packages\msrest\service_client.py", line 219, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "c:\users\cvcdev\appdata\local\programs\python\python36-32\lib\site-packages\msrest\pipeline\__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "c:\users\cvcdev\appdata\local\programs\python\python36-32\lib\site-packages\msrest\pipeline\__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "c:\users\cvcdev\appdata\local\programs\python\python36-32\lib\site-packages\msrest\pipeline\requests.py", line 72, in send
    return self.next.send(request, **kwargs)
  File "c:\users\cvcdev\appdata\local\programs\python\python36-32\lib\site-packages\msrest\pipeline\requests.py", line 137, in send
    return self.next.send(request, **kwargs)
  File "c:\users\cvcdev\appdata\local\programs\python\python36-32\lib\site-packages\msrest\pipeline\__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "c:\users\cvcdev\appdata\local\programs\python\python36-32\lib\site-packages\msrest\pipeline\requests.py", line 193, in send
    self.driver.send(request.http_request, **kwargs)
  File "c:\users\cvcdev\appdata\local\programs\python\python36-32\lib\site-packages\msrest\universal_http\requests.py", line 328, in send
    return super(RequestsHTTPSender, self).send(request, **requests_kwargs)
  File "c:\users\cvcdev\appdata\local\programs\python\python36-32\lib\site-packages\msrest\universal_http\requests.py", line 137, in send
    **kwargs)
  File "c:\users\cvcdev\appdata\local\programs\python\python36-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\cvcdev\appdata\local\programs\python\python36-32\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\cvcdev\appdata\local\programs\python\python36-32\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "c:\users\cvcdev\appdata\local\programs\python\python36-32\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "c:\users\cvcdev\appdata\local\programs\python\python36-32\lib\site-packages\urllib3\connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "c:\users\cvcdev\appdata\local\programs\python\python36-32\lib\site-packages\urllib3\connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "c:\users\cvcdev\appdata\local\programs\python\python36-32\lib\site-packages\urllib3\connection.py", line 344, in connect
    ssl_context=context)
  File "c:\users\cvcdev\appdata\local\programs\python\python36-32\lib\site-packages\urllib3\util\ssl_.py", line 335, in ssl_wrap_socket
    context.load_cert_chain(certfile, keyfile)
  File "c:\users\cvcdev\appdata\local\programs\python\python36-32\lib\site-packages\urllib3\contrib\pyopenssl.py", line 433, in load_cert_chain
    self._ctx.use_certificate_chain_file(certfile)
  File "c:\users\cvcdev\appdata\local\programs\python\python36-32\lib\site-packages\OpenSSL\SSL.py", line 913, in use_certificate_chain_file
    _raise_current_error()
  File "c:\users\cvcdev\appdata\local\programs\python\python36-32\lib\site-packages\OpenSSL\_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('PEM routines', 'PEM_read_bio', 'no start line'), ('SSL routines', 'use_certificate_chain_file', 'PEM lib')]

**Comment by Christina-Kang** [comment]
@binishababu, thanks for reporting! 

It looks like there is an issue with your pem file.

`OpenSSL.SSL.Error: [('PEM routines', 'PEM_read_bio', 'no start line'), ('SSL routines', 'use_certificate_chain_file', 'PEM lib')]`

If you've checked that the file is correct, let me know and we can look into this further.
