### ISSUE TITLE
"(E_INVALIDARG) Invalid argument" sfctl compose create

### ISSUE THREAD

**Issue by Liamdelee** [Microsoft/service-fabric-cli#171]
When reporting a new issue include the following information:

sfctl verion: 7.0.1
service Fabric Cluster runtime version: 6.4.625.1
service Fabric Cluster OS: ubuntuServer 16.04-LTS
Service Fabric hosting location: Azure
Debug log:
```
Command arguments: ['compose', 'create', '--deployment-name', 'bridgestonewebapp', '--file-path', 'docker-compose.yml', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x0502B4F8>, <function OutputProducer.on_global_arguments at 0x0508C270>, <function CLIQuery.on_global_arguments at 0x050A5BB8>]
Event: CommandInvoker.OnPreCommandTableCreate []
Event: CommandLoader.OnLoadArguments []
Event: CommandInvoker.OnPostCommandTableCreate []
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs []
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x0508C2B8>, <function CLIQuery.handle_query_parameter at 0x050A5C00>]
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
msrest.service_client : Accept header absent and forced to application/json
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): bridgestonewebapp.northeurope.cloudapp.azure.com:19080
c:\users\deleeli\appdata\local\programs\python\python37-32\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
urllib3.connectionpool : https://bridgestonewebapp.northeurope.cloudapp.azure.com:19080 "PUT /Explorer/ComposeDeployments/$/Create?api-version=6.0-preview&timeout=60 HTTP/1.1" 400 62
msrest.exceptions : (E_INVALIDARG) Invalid argument
(E_INVALIDARG) Invalid argument
Traceback (most recent call last):
  File "c:\users\deleeli\appdata\local\programs\python\python37-32\lib\site-packages\knack\cli.py", line 206, in invoke
    cmd_result = self.invocation.execute(args)
  File "c:\users\deleeli\appdata\local\programs\python\python37-32\lib\site-packages\knack\invocation.py", line 188, in execute
    cmd_result = parsed_args.func(params)
  File "c:\users\deleeli\appdata\local\programs\python\python37-32\lib\site-packages\knack\commands.py", line 105, in __call__
    return self.handler(*args, **kwargs)
  File "c:\users\deleeli\appdata\local\programs\python\python37-32\lib\site-packages\knack\commands.py", line 212, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "c:\users\deleeli\appdata\local\programs\python\python37-32\lib\site-packages\sfctl\custom_compose.py", line 78, in create
    client.create_compose_deployment(desc, timeout=timeout)
  File "c:\users\deleeli\appdata\local\programs\python\python37-32\lib\site-packages\azure\servicefabric\service_fabric_client_ap_is.py", line 9509, in create_compose_deployment
    raise models.FabricErrorException(self._deserialize, response)
azure.servicefabric.models.fabric_error_py3.FabricErrorException: (E_INVALIDARG) Invalid argument
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
msrest.universal_http.requests : Configuring retry: max_retries=3, backoff_factor=0.8, max_backoff=90
Performing cluster version check
msrest.universal_http : Configuring redirects: allow=True, max=30
msrest.universal_http : Configuring request: timeout=100, verify=True, cert=None
msrest.universal_http : Configuring proxies: ''
msrest.universal_http : Evaluate proxies against ENV settings: True
urllib3.connectionpool : Starting new HTTPS connection (1): bridgestonewebapp.northeurope.cloudapp.azure.com:19080
c:\users\deleeli\appdata\local\programs\python\python37-32\lib\site-packages\urllib3\connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
urllib3.connectionpool : https://bridgestonewebapp.northeurope.cloudapp.azure.com:19080 "GET /Explorer/$/GetClusterVersion?api-version=6.4&timeout=60 HTTP/1.1" 400 62
msrest.exceptions : (E_INVALIDARG) Invalid argument
Check cluster version failed due to error: <class 'azure.servicefabric.models.fabric_error_py3.FabricErrorException'>
```

I want to compose my docker image to the service fabric cluster but i get the above error.
HOWEVER, when i do it manually inside of service fabric and do "create compose application" and use the exact same docker-compose.yml file it works out great with no error.
Please help me forward because i want to script this for ease of use.
Thanks
Liam

**Comment by Christina-Kang** [comment]
Hi @Liamdelee 

Since connecting to this endpoint, have any sfctl commands worked for you? Is this the first you've tried since connecting?

From the looks of things, an extra "Explorer" is being appended to the HTTP request, which is causing it to return INVALID_ARGUMENT. It's possible that the endpoint you've set has that appended at the end. You can check this by using `sfctl cluster show-connection`. If it does, remove that by running `sfctl cluster select` again, and let me know if the compose command works for you now.

The endpoint should have the format `http://<your URL>:19080`

Thanks,
Christina

**Comment by Liamdelee** [comment]
Hi @Christina-Kang 

I had explorer appended after the url with the select that i found as an example on the internet.
Thanks for your help!
And have great holidays!

Best regards
Liam

**Comment by Christina-Kang** [comment]
Glad to hear it's working now, and happy holidays to you as well!
