### ISSUE TITLE
Windows Install Failure

### ISSUE THREAD

**Issue by pbaumgartner-rdt** [microsoft/service-fabric-cli#261]
My issue occurs with a fresh install of `sfctl` from `pip` on Windows 10.

Attempting a call of `sfctl -h` results in the error stack below.
```
python --version 
> Python 3.12.6
pip --version
> pip 24.2 from C:\Users\me\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip (python 3.12)
```
- [X] `sfctl` version, can check this using `pip show sfctl`
```
Name: sfctl
Version: 10.0.0
Summary: Azure Service Fabric command line
Home-page: https://github.com/Azure/service-fabric-cli
Author: Microsoft Corporation
Author-email: sfpythoncli@microsoft.com
License: MIT
Location: C:\Users\me\AppData\Local\Programs\Python\Python312\Lib\site-packages
Requires: adal, applicationinsights, azure-servicefabric, future, knack, msrest, msrestazure, portalocker, psutil, requests, sfmergeutility, six
Required-by:
```
- [X] Service Fabric cluster runtime version

10.0.1949.9590

- [X] Service Fabric hosting location (on-premise or Azure usually)

On premises (local development single node Windows cluster)

- [X] Debug log if an error is present (can be captured using `--debug` flag)
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\me\AppData\Local\Programs\Python\Python312\Scripts\sfctl.exe\__main__.py", line 4, in <module>
  File "C:\Users\me\AppData\Local\Programs\Python\Python312\Lib\site-packages\sfctl\__init__.py", line 16, in <module>
    from sfctl.entry import launch
  File "C:\Users\me\AppData\Local\Programs\Python\Python312\Lib\site-packages\sfctl\entry.py", line 17, in <module>
    from sfctl.custom_cluster import check_cluster_version
  File "C:\Users\me\AppData\Local\Programs\Python\Python312\Lib\site-packages\sfctl\custom_cluster.py", line 18, in <module>
    from sfctl.state import get_sfctl_version
  File "C:\Users\me\AppData\Local\Programs\Python\Python312\Lib\site-packages\sfctl\state.py", line 12, in <module>
    from pkg_resources import get_distribution
ModuleNotFoundError: No module named 'pkg_resources'

```

**Comment by niklasholm** [comment]
I have the same problem, did you find a solution?

**Comment by kthomas22** [comment]
pip install setuptools==81.0.0

using any version above 81 doesn't work
