### ISSUE TITLE
Deleting a non existent application returns an invalid status code

### ISSUE THREAD

**Issue by samedder** [Microsoft/service-fabric-cli#31]
When deleting an application that does not exist the response code appears to be invalid:

```
Operation returned an invalid status code 'Not Found'
Traceback (most recent call last):
  File "/home/imang/.local/lib/python3.5/site-packages/knack/cli.py", line 125, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/imang/.local/lib/python3.5/site-packages/knack/invocation.py", line 85, in execute
    cmd_result = parsed_args.func(params)
  File "/home/imang/.local/lib/python3.5/site-packages/knack/commands.py", line 67, in __call__
    return self.handler(*args, **kwargs)
  File "/home/imang/.local/lib/python3.5/site-packages/knack/commands.py", line 123, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "/home/imang/.local/lib/python3.5/site-packages/azure/servicefabric/service_fabric_client_ap_is.py", line 3128, in delete_application
    raise models.FabricErrorException(self._deserialize, response)
azure.servicefabric.models.fabric_error.FabricErrorException: Operation returned an invalid status code 'Not Found'
```

The API does not expect to return a 404 status code.

**Comment by jeffj6123** [comment]
Issue has been fixed.
