### ISSUE TITLE
Attempting to provision the same application package twice results in an invalid status code

### ISSUE THREAD

**Issue by samedder** [Microsoft/service-fabric-cli#32]
When calling `application provision` on an application type that has already been provisioned, an invalid response code of 409 is returned.

```
Operation returned an invalid status code 'Conflict'
Traceback (most recent call last):
  File "/home/imang/.local/lib/python3.5/site-packages/knack/cli.py", line 125, in invoke
    cmd_result = self.invocation.execute(args)
  File "/home/imang/.local/lib/python3.5/site-packages/knack/invocation.py", line 85, in execute
    cmd_result = parsed_args.func(params)
  File "/home/imang/.local/lib/python3.5/site-packages/knack/commands.py", line 67, in __call__
    return self.handler(*args, **kwargs)
  File "/home/imang/.local/lib/python3.5/site-packages/knack/commands.py", line 123, in _command_handler
    result = op(client, **command_args) if client else op(**command_args)
  File "/home/imang/.local/lib/python3.5/site-packages/azure/servicefabric/service_fabric_client_ap_is.py", line 2613, in provision_application_type
    raise models.FabricErrorException(self._deserialize, response)
azure.servicefabric.models.fabric_error.FabricErrorException: Operation returned an invalid status code 'Conflict'
```

This is a bug in the API specification for `application provision`.

**Comment by iyyappam** [comment]
Internal bug 10301848 filed.

**Comment by Christina-Kang** [comment]
The error message being returned currently is `(FABRIC_E_APPLICATION_TYPE_ALREADY_EXISTS) Application type and version already exists` (as of version 5.0.0).

@Capotasto Sorry for missing your post earlier! The issue should have been fixed for a while; can you update to the latest version (5.0.0) and see if that fixes your issue? If not, please re-open this or create a new issue and tag me. Thanks!
